version: '3' 

services:
    middleware:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: 'spring-boot-redis-cache-container'
        image : spring-boot-redis-cache-image
        volumes:
            - ./config:/usr/local
        ports:
            - "8083:8083"
        links:
            - "master"
            - "slave-1"
    master:
        container_name: master
        image: redis:6
        ports:
          - 6379:6379
    slave-1:
        container_name: slave-1
        image: redis:6
        ports:
          - 6380:6380
        command: redis-server --slaveof master 6379 --port 6380 --slave-announce-ip 127.0.0.1
                
                