server:
  port: 8083

spring:
  redis:
    master:
      host: 172.21.101.40
      port: 12002
    slaves:
      - host: 172.21.101.38
        port: 12002
    lettuce:
      pool:
        max-active: 200
        max-idle: 200
    timeout: 30000