server:
  port: 8083

spring:
  redis:
    password: 52wJmtmEVuAsL
    master:
      host: 172.21.101.40
      port: 12002
    slaves:
      - host: 172.21.101.38
        port: 12002
    timeout: 30000